### ISSUE TITLE
Rimworld progress tracker.

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#317]
Ref: http://piratepad.net/4BHeoNAPYn

**Standard Sci-Fi + Wild West clothes**
- [ ] Trenchcoats, dusters
- [x] Cowboy hats, cowboy boots
- [x] bandanas
- [ ] semi-formal wear (think the "watering hole proprietor" look)
- [x] sunglasses
- [ ] combat goggles
- [ ] baseball caps, business suits
- [x] vests
- [x] Malcom Reynolds' clothes
- [ ] holster belts
- [ ] bandoliers, etc.

**Basic armor**
- [x] Kevlar vests
- [ ] armored longcoats
- [ ] padded clothing
- [ ] steel helmets
- [x] combat helmets

**Improvised:**
- [x] Improvised metal armour
- [ ] Craftable leather armor
- [ ] hardened leather stab vests, etc.

**Fancy armour (events, important people):**
- [x] Bulletproof vests
- [x] ablative armor
- [ ] surplus ERT/merc vests
- [x] tactical armor
- [ ] hardsuits
- [ ] SWAT helmets

**Melee weapons:**
- [x] switchblades
- [x] pocket knives
- [x] baseball bats
- [x] knuckledusters
- [x] trench knives
- [ ] power fists
- [ ] lengths of pipe
- [x] obvious swords

**Common guns (.357, .45, 9mm, basic calibers):**
- [x] Semi-auto pistols
- [x] sixshooters
- [x] SMGs
- [x] tasers

**Long guns (uncommong):**
- [x] Semi-auto long rifles (like AK-47s and SKS rifles)
- [x] shotguns (pump and double-barrel)

**Improvised guns:**
Second-rate firearms made of steel, wooden stocks, plastic, and other cheap products. Pipe rifles and shotguns and other dangerously unstable weapons.
This could be done by adding improvised components to the general gun system (Polaris code) and porting it over (which is intended anyway).

**Uncommon guns:**
- [x] Scoped rifles, 
- [x] semi-auto shotguns

**Rare guns:**
- [x] Most energy weapons
- [x] PTR-7 rifles
- [x] and other incredibly strong/expensive weapons

**Explosives (probably pretty rare)**
SS13 bombs (HE, flashbangs, smoke, C4 the usual stuff), dynamite

**Resources:**

The place should be mostly self-sufficient, using merchants/ruins for more advanced/luxury goods

- [x] Mining for ores (obv.)
- [x] Cutting trees for wood
- [x] Farming on the plain dirt for food (possibly able to buy hydro trays from merchants)
- [x] Scrapping ruins/crashed ships/etc. for materials

**Other features:**
- [x] Seeing and moving across z-levels without using stairs or ladders (climbing) (SERIOUS ENDGAME GOAL)
- [x] Finding a way to both build in space and on the planet while maintaining the appropriate base turf (endgame goal)
- [ ] Random generator for the wilds/abandoned corporate bases/etc.
- [ ] New events (slaver/pirate raids, exotic goods traders/arms dealers coming in from space, dust storms, etc.)

**Scrapping (the bones of civilization)**
- Randomly-placed scrap. 
- Scrap ranges from one or two piles of "scrap" objects (interact to pull out random raw materials and junk until it depletes) to crumbling buildings to entire shuttles or pieces of larger ships, made of metal and possibly some useful manufactured products inside. 
- Woodcutters/scrappers will be the same role in the town, with miners being their own. 

**Jobs:**
- [x] Governor - Runs the settlement like a boss.
- [x] Vagrant - Does stuff they wanna do. Default assistant role.
- [x] Colonist - Basically a vagrant with a position in the town/limited numbers.
- [x] Blast Miner - Mines up ore.
- [x] Farmer - Farms the farm.
- [x] Mechanic - Builds people vehicles for a reasonable price.
- [x] Merchant - Buys and sells goods. Direct access with trader.
- [x] Scrapper - Adventures off to scrap in the dangerours scrap zones.
- [x] Hunter - Hunts danger. Breeds kills, breeds kills.
- [x] Lawman - Protects the town.
- [X] Sawbones - Town doctor.

**Launch Map** - 70%
- [x] Basic geometry.
- [x] Areas.
- [x] Highway rest stop.
- [x] Job and latejoin spawn landmarks.
- [x] Appropriate spawn points for entering/leaving the map.
- [ ] Decorative bits.
- [x] Ambient sound and effects.
- [x] Global lighting (sunset etc)

**Launch Vehicles** - 10%
- [X] Make bikes more meaty. Larger sprite, sound effects, collision mechanics.
- [ ] Make bikes respect speed/momentum and continue moving in the direction pointed (use walk_to()?)
- [ ] Make bikes constructable.
- [ ] Add passenger capacity and gunnery to vehicles.
- [ ] Add larger vehicles (cars, trucks).
- [ ] Add vehicle storage and trailers.
- [ ] Add coverage and vehicle armour.
- [ ] Add vehicle construction and maintenance mechanics.
- [ ] Integrate vehicles and mechs.

**Launch Weapons** - 0%
- [x] Ballistic firearms.
- [x] Energy weapons.
- [ ] Exotic weapons.
- [ ] Improvised melee and ballistic weapons.
- [x] Swords and knives.
- [ ] TODO

**Crafting System** - 0%
- [x] Add gun crafting.
- [ ] TODO

**Scrapping System** - 5%
- [X] Add random debris piles.
- [ ] Add salvage site generator.
- [ ] Add marketplace for selling scrap.

**Weather System**- 0%
- [ ] TODO

**Comment by Loganbacca** [comment]
Yay! Firefly ~~station~~ settlement 13!

:+1:

**Comment by Zuhayr** [comment]
Immediate shit to do:

- [ ] add harvestable wild plants/bushes
- [ ] add huntable flora (ask Nien for deer and fox sprites?)
- [ ] add hostile feral predators (bears in forest, coyotes in desert?)
- [ ] add fishing?
- [ ] add wooden 'scaffold' girder object that can be used to build walls
- [X] add concrete material
- [X] add bonfires/hearth fires (steal from vg?)
- [ ] add ability to bash down walls with melee
- [ ] work out why the mining map isn't generating ore.
- [ ] fix explosions to open holes in the ground so strip mining is possible
- [ ] Investigate using client.color to set environmental lighting effects.

**Comment by Vivalas** [comment]
So I'm curious as to what exactly this is, a diversion from Europa to blow off steam or what? Anyways sounds very fun, can't wait to robust some boomrats.

**Comment by Zuhayr** [comment]
Basically I was stalling out on the flooding/water aspects of the map so we decided to make a new map this month using Nienhaus' space cowboy project idea. It's 90% stuff that will be used on the main water map; I want this codebase to function well as a general planetary codebase, so this is a good test.

**Comment by Zuhayr** [comment]
#417
