### ISSUE TITLE
510 lighting TODO

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#387]
- [ ] Non-dynamic area lighting overlays.
- [x]  PLANE_MASTER mob rotation bug.
- [x] Cell background images for w_class-based storage objects are still plane 0 instead of 10.
- [x] Directional icons for lights are shit. Replace them.
- [x] Fix composite gun icons properly.
- [x] Do something about light bleed.

**Comment by Zuhayr** [comment]
Fixes are in #392
