### ISSUE TITLE
Rimworld progress tracker

### ISSUE THREAD

**Issue by Loganbacca** [Yonaguni/EuropaStation#417]
## Features
- [ ] Atmospherics
- [ ] Cooking
- [ ] Hunting
- [ ] Lighting
- [ ] Mob AI
- [ ] Salvage system (including site generator and marketplace)
- [ ] Weather system
- [ ] Random generator for the wilds, abandoned corporate bases, etc.
- [ ] New events (slaver/pirate raids, exotic goods traders, arms dealers coming in from space, dust storms, etc.)

## Content
- [ ] More animals
- [ ] Trenchcoats, dusters
- [ ] semi-formal wear (think the "watering hole proprietor" look)
- [ ] combat goggles
- [ ] baseball caps, business suits
- [ ] holster belts
- [ ] bandoliers, etc.
- [ ] armored longcoats
- [ ] padded clothing
- [ ] steel helmets
- [ ] Craftable leather armor
- [ ] hardened leather stab vests, etc.
- [ ] surplus ERT/merc vests
- [ ] hardsuits
- [ ] SWAT helmets
- [ ] power fists
- [ ] lengths of pipe
- [ ] dynamite
- [ ] Decorative bits for the map
- [ ] Exotic weapons
- [ ] Improvised melee and ballistic weapons

## Vehicles
- [ ] Make vehicles respect speed/momentum and continue moving in the direction pointed (use walk_to()?)
- [ ] Make bikes constructable
- [ ] Add passenger capacity and gunnery to vehicles
- [ ] Add larger vehicles (cars, trucks)
- [ ] Add vehicle storage and trailers
- [ ] Add coverage and vehicle armour
- [ ] Add vehicle construction and maintenance mechanics
- [ ] Integrate vehicles and mechs

**Comment by Zuhayr** [comment]
Copied from the previous tracker:
- [ ] Trenchcoats, dusters
- [ ] semi-formal wear (think the "watering hole proprietor" look)
- [ ] combat goggles
- [ ] baseball caps, business suits
- [ ] holster belts
- [ ] bandoliers, etc.
- [ ] armored longcoats
- [ ] padded clothing
- [ ] steel helmets
- [ ] Craftable leather armor
- [ ] hardened leather stab vests, etc.
- [ ] surplus ERT/merc vests
- [ ] hardsuits
- [ ] SWAT helmets
- [ ] power fists
- [ ] lengths of pipe
- [ ] dynamite
- [ ] Random generator for the wilds/abandoned corporate bases/etc.
- [ ] New events (slaver/pirate raids, exotic goods traders/arms dealers coming in from space, dust storms, etc.)
- [ ] Decorative bits for the map.
- [ ] Make bikes respect speed/momentum and continue moving in the direction pointed (use walk_to()?)
- [ ] Make bikes constructable.
- [ ] Add passenger capacity and gunnery to vehicles.
- [ ] Add larger vehicles (cars, trucks).
- [ ] Add vehicle storage and trailers.
- [ ] Add coverage and vehicle armour.
- [ ] Add vehicle construction and maintenance mechanics.
- [ ] Integrate vehicles and mechs.
- [ ] Exotic weapons.
- [ ] Improvised melee and ballistic weapons.
- [ ] Add salvage site generator.
- [ ] Add marketplace for selling scrap.
- [ ] Weather system

**Comment by Loganbacca** [comment]
Oops, I totally forgot there was already another one of these. Even named the same.

**Comment by Loganbacca** [comment]
I'm going to retire this for now.
