### ISSUE TITLE
[TODO] Loganbacca

### ISSUE THREAD

**Issue by Loganbacca** [Yonaguni/EuropaStation#469]
Just a list of stuff I intend to do:
- [ ] Terminals <- actually working on this
- [ ] Planar lighting shadows
- [ ] Input/character control rewrite
- [ ] UI rewrite

**Comment by Zuhayr** [comment]
RIP Logan.

**Comment by Loganbacca** [comment]
Yea, I cant bring myself to BYOND anymore.
